/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Product;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-09-24T16:26:29.294335690Z[GMT]")
@Validated
public interface ProductApi {

    @Operation(summary = "Alle Produkte abrufen", description = "", tags={ "Produkt" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Erfolgreiche Abfrage"),
        
        @ApiResponse(responseCode = "201", description = "Erfolgreich erstellt"),
        
        @ApiResponse(responseCode = "400", description = "Ungültige Anfrage") })
    @RequestMapping(value = "/product",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Void> productGet();


    @Operation(summary = "Produkt mit ID abrufen", description = "", tags={ "Produkt" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Erfolgreiche Abfrage"),
        
        @ApiResponse(responseCode = "400", description = "Ungültige Anfrage"),
        
        @ApiResponse(responseCode = "404", description = "Produkt nicht gefunden") })
    @RequestMapping(value = "/product/{id}",
        method = RequestMethod.GET)
    ResponseEntity<Void> productIdGet(@Parameter(in = ParameterIn.PATH, description = "ID des Produkts", required=true, schema=@Schema()) @PathVariable("id") Object id);


    @Operation(summary = "Neues Produkt erstellen", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Erfolgreich erstellt"),
        
        @ApiResponse(responseCode = "400", description = "Ungültige Anfrage") })
    @RequestMapping(value = "/product",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> productPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Product body);

}

