openapi: 3.1.0
info:
  title: MiniShop-API
  version: 1.0.0
  contact:
    name: GruppeA SWAD
servers:
  - url: https://api.example.com/
paths:
  /user:
    post:
      tags:
        - User
      summary: Registrierung eines neuen Benutzers
      requestBody:
            required: true
            content:
             application/json:
              schema:
                $ref: '#/components/schemas/User'
      responses:
            '200':
              description: Registrierung erfolgreich
              content:
                application/json:
                 schema:
                  type: object
                  properties:
                    message:
                        type: string
                        example: Registrierung erfolgreich
            '400':
              description: Registrierung fehlgeschlagen (Benutzername bereits vergeben)

    get:
      tags:
        - User
      summary: Benutzerdaten abrufen
      responses:
        '200':
          description: Benutzerdaten erfolgreich abgerufen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /user/login:
    get:
      summary: Login des Mini-Shops
      responses:
        '200':
          description: Login erfolgreich
          content:
            application/json:
              example:
                $ref: '#/components/schemas/Login'
        '401':
          description: Login fehlgeschlagen



  /product:
    get:
      tags:
        - Produkt
      summary: Alle Produkte abrufen
      responses:
        '200':
          description: Erfolgreiche Abfrage
          content:
            application/json:
              example:
                $ref: '#/components/schemas/Product'
        '201':
          description: Erfolgreich erstellt
        '400':
          description: Ungültige Anfrage
    post:
      summary: Neues Produkt erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Erfolgreich erstellt
        '400':
          description: Ungültige Anfrage

components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          format: email
          example: test@gmail.com
        username:
          type: string
          example: Max Mustermann
        password:
          type: string
          format: password
          maxLength: 8
          example: 123456
        password2:
          type: string
          format: password
          maxLength: 8
          example: 123456
    Product:
      type: object
      properties:
        name:
          type: string
          example: Fruit Packet
        price:
          type: number
          example: 43.60
        weight:
          type: number
          example: 500

    Login:
        type: object
        properties:
          username:
            type: string
            example: Max Mustermann
          password:
            type: string
            format: password
            maxLength: 8
            example: 123456


