openapi: 3.1.0
info:
  title: MiniShop-API
  version: 1.0.0
  contact:
    name: GruppeA SWAD
servers:
  - url: https://api.example.com/
paths:
  /user:
    post:
      tags:
        - User
      summary: Registrierung eines neuen Benutzers
      requestBody:
            required: true
            content:
             application/json:
              schema:
                $ref: '#/components/schemas/User'
      responses:
            '200':
              description: Registrierung erfolgreich
              content:
                application/json:
                 schema:
                  type: object
                  properties:
                    message:
                        type: string
                        example: Registrierung erfolgreich
            '400':
              description: Registrierung fehlgeschlagen (Benutzername bereits vergeben)
              content:
               application/json:
                schema:
                 type: object
                 properties:
                  message:
                   type: string
                   example: Registrierung fehlgeschlagen
    get:
      tags:
        - User
      summary: Benutzerdaten abrufen
      responses:
        '200':
          description: Benutzerdaten erfolgreich abgerufen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /login:
    get:
      summary: Login des Mini-Shops
      responses:
        '200':
          description: Login erfolgreich
          content:
            application/json:
              example:
                - id: 1
                  username: Max Mustermann
                  password: 123456
                - id: 2
                  username: Max Musterfrau
                  password: 654321
        '401':
          description: Login fehlgeschlagen
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login fehlgeschlagen

  /pw-reset:
    put:
      summary: Passwort zurücksetzen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Passwort zurückgesetzt
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Passwort zurückgesetzt
        '400':
          description: Passwort zurücksetzen fehlgeschlagen
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Passwort zurücksetzen fehlgeschlagen
  /product:
    get:
      tags:
        - Produkt
      summary: Produkte
      responses:


components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          format: email
          example: test@gmail.com
        username:
          type: string
          example: Max Mustermann
        password:
          type: string
          format: password
          maxLength: 8
          example: 123456
        password2:
          type: string
          format: password
          maxLength: 8
          example: 123456