/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Product;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-09-27T17:52:30.403097720Z[GMT]")
@Validated
public interface ProductApi {

    @Operation(summary = "Produkt mit ID abrufen", description = "", tags={ "Produkt" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Erfolgreiche Abfrage"),
        
        @ApiResponse(responseCode = "400", description = "Ungültige Anfrage"),
        
        @ApiResponse(responseCode = "404", description = "Produkt nicht gefunden") })
    @RequestMapping(value = "/product/{productId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Void> getProductById(@Parameter(in = ParameterIn.PATH, description = "ID des Produkts", required=true, schema=@Schema()) @PathVariable("productId") Long productId);


    @Operation(summary = "Alle Produkte abrufen", description = "", tags={ "Produkt" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Erfolgreiche Abfrage"),
        
        @ApiResponse(responseCode = "201", description = "Erfolgreich erstellt"),
        
        @ApiResponse(responseCode = "400", description = "Ungültige Anfrage") })
    @RequestMapping(value = "/product",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Void> productGet();


    @Operation(summary = "Neues Produkt erstellen", description = "", tags={ "Produkt" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Erfolgreich erstellt"),
        
        @ApiResponse(responseCode = "400", description = "Ungültige Anfrage") })
    @RequestMapping(value = "/product",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> productPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Product body);

}

